name: Deploy web app to GitHub Pages

on:
  push:
    branches:
      - main # 當你推送（push）程式碼到 main 分支時會自動觸發此部署流程

# 給予 GitHub Action 必要權限以將編譯後的網站推送至 gh-pages 頁面
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-cache: 'npm'
          node-version: 20

      - name: Install Dependencies
        run: npm ci

      - name: Build Application
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Vite 編譯後的輸出資料夾路徑
          branch: gh-pages # 要部署的目的地分支名（GitHub Pages 預設讀取分支）
